from google.adk.agents.llm_agent import LlmAgent
from .tools import search_tool, github_mcp_tools, read_text, write_text, list_directory, run_command

MODEL = 'gemini-2.5-flash'

researcher_agent = LlmAgent(
    name='researcher_agent',
    model=MODEL,
    description='A research expert agent',
    instruction="""
        You are part of a multi-agent tean whose goal is to identify software bugs and provide solutions
        Your job is to perform a google search on the related problem.
        The google search should include common solutions to the problem and github Repos and online docs that might help solve
    """,
    tools=[search_tool]
)

file_analyser_agent = LlmAgent(
    name='file_analyser_agent',
    model=MODEL,
    description='A file analysis agent',
    instruction='You are part of a multi-agent tean whose goal is to identify software bugs and provide solutions. Your job is to perform file operations like reading text or listing directories to help solve the problem. You can also run cmd commands to check for errors. You only deal with file-related, local problems',
    tools=[read_text, list_directory, run_command]
)

github_agent = LlmAgent(
    name='github_agent',
    model=MODEL,
    description='A GitHub analysis agent',
    instruction="""
        You are part of a multi-agent tean whose goal is to identify software bugs and provide solutions.
        Your job is to return info about certain GitHub repositories as inquired by the user.
        You are to answer questions about GitHub repos giving the user quality info
        You can also read PRs, merges, commits and other stuff to solve the bugs in the requested repo(s).
        If there is a file based problem you can also read repos to solbe it
    """,
    tools=[read_text, github_mcp_tools]
)


root_agent = LlmAgent(
    model=MODEL,
    name='root_agent',
    description='A helpful software bug assistant.',
    instruction=f"""
        You are an orchestrator of a multi-agent tean whose goal is to identify software bugs and provide solutions.
        You use {researcher_agent} for research on the presented problem,
        You should use {file_analyser_agent} for file based problem solving..
        You can also use {github_agent} for GitHub repo analysis for aid in the problem solving..
        Use the write_text tool for creating reports on the bugs and how to fix them
        Then use read_text tool to read the bug report generated by the write_text tool
    """,
    sub_agents=[researcher_agent, file_analyser_agent, github_agent],
    tools=[read_text, write_text]
)
